name: GitHub Actions Demo
on:
  push:
 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - run: echo "The job was automatically triggered by a ${{ secrets.AM }} event."
      - run: echo "The job was automatically triggered by a ${{ vars.MY_AM }} event."
